### ISSUE TITLE
Add bot for labels

### ISSUE THREAD

**Issue by StantStantov** [Contributors-pi8/pi8-spbstu-labs#17]
Связи с появлением ярлыков для различных предметов можно попробовать добавить бота, который будет выставлять их за нас. GitHub предоставляет такую возможность, поэтому не вижу ничего плохого в его появление.

Ваши мысли и предложения?

**Comment by imKamikoto** [comment]
идея классная. во. супер, я за. если хочешь сделать - делай =)
